### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by kjagoo** [Elbertbiggs360/buckelist-api#4]
POST /auth/register - unsure that the username field is unique - this avoids duplicate entrys
POST /bucketlists/ - when successfull "have a message to show this with status 200"
GET /bucketlists/ - ensure that if empty "you can display something to say its empty"
GET /bucketlists/<id> -  ensure if the `id ` is not available , "you have a way to display this"
POST /bucketlists/<id>/items/
PUT /bucketlists/<id>/items/<item_id> - when updated 
PUT /bucketlists/<id>

**Comment by Elbertbiggs360** [comment]
POST /auth/register is complete

**Comment by Elbertbiggs360** [comment]
POST /bucketlists/ is complete

**Comment by Elbertbiggs360** [comment]
EDIT /bucketlists/ is done
DELETE /bucketlists/ is done

**Comment by Elbertbiggs360** [comment]
PUT /bucketlists/items/<item_id>
DELETE /bucketlists/items/<item_id>
GET /bucketlists/items/<item_id>
GET /bucketlists/items/
