### ISSUE TITLE
Pending functionalities

### ISSUE THREAD

**Issue by kjagoo** [Elbertbiggs360/buckelist-api#9]
1. Token based authorisation.
2.  Migration Scripts,
3. Tests 
4. Require Code review
5. Pagination
6. Search

**Comment by Elbertbiggs360** [comment]
### Finished
 - token based authorization
- Migration scripts modified

**Comment by Elbertbiggs360** [comment]
### In development 
- Written extra tests ✅

**Comment by Elbertbiggs360** [comment]
## Finished
Search 🕵🏽 and Pagination 📄 Complete
